---

- hosts: all
  gather_facts: true
  become: true

  vars:
    kvm: "{{lookup('env', 'KVM')|default('false')}}"

  pre_tasks:
  - assert:
      that:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version == "20.04"
        - ansible_user == "ubuntu"

  tasks:
  - name: Include os-tuning role
    include_role:
      name: os-tuning
      tasks_from: main.yml

  - name: Enable virtual console for KVM guests
    include_role:
      name: kvm-guest
      tasks_from: vconsole.yml
    when: kvm|bool

  - name: Set NOPASSWD for {{ansible_user}}
    lineinfile:
      path: "/etc/sudoers.d/{{ansible_user}}"
      regexp: 'ubuntu\sALL='
      line: 'ubuntu ALL=(ALL:ALL) NOPASSWD:ALL'
      state: present
      create: yes
      validate: 'visudo -cf %s'

  - name: Install packages
    apt:
      name:
        - git
        - sshpass
        - make
        - python3-pip
        - apt-transport-https
        - ca-certificates
        - curl
      state: latest
      update_cache: yes
    register: _install_pkg
    retries: 3
    delay: 5
    until: _install_pkg is success
