---

- hosts: all
  gather_facts: true

  vars:
    cleanup: false
    OSH_EXTRA_HELM_ARGS: "--timeout 20m"
    OPENSTACK_RELEASE: 'victoria'
    CONTAINER_DISTRO_VERSION: 'focal'
    UPDATE_CALICO_VERSION: "true"
    osh_repos:
      - name: infra
        repo: "https://opendev.org/openstack/openstack-helm-infra.git"
        dest: "{{ansible_env.HOME}}/openstack-helm-infra"
      - name: component
        repo: "https://opendev.org/openstack/openstack-helm.git"
        dest: "{{ansible_env.HOME}}/openstack-helm"

  tasks:
  - include_tasks: additional/minikube-cleanup.yml
    when: cleanup|bool

  - name: Set hostname
    hostname:
      name: "{{inventory_hostname}}"
      use: systemd
    become: true

  - name: Start systemd-resolved
    systemd:
      name: systemd-resolved
      state: started
    become: true

  - name: Add '127.0.1.1 {{inventory_hostname}}' in /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^127.0.1.1'
      line: '127.0.1.1 {{inventory_hostname}}'
      state: present
    become: true

  - name: Copy /run/systemd/resolve/resolv.conf to /etc/resolv.conf
    copy:
      src: /run/systemd/resolve/resolv.conf
      dest: /etc/resolv.conf
      remote: yes
      owner: root
      group: root
    become: yes

  - name: Start systemd-resolved
    systemd:
      name: systemd-resolved
      state: stopped
      enabled: no
    become: true

  - name: clone openstack helm code
    shell: git clone {{item.repo}} {{item.dest}}
    with_items: "{{osh_repos}}"
    register: _clone
    retries: 3
    delay: 5
    until: _clone is success

  - name: Install Minikube
    shell: ./tools/gate/deploy-k8s.sh
    args:
      chdir: "{{ansible_env.HOME}}/openstack-helm"
