---

- hosts: all
  gather_facts: true

  vars:
    HELM_TESTS: no
    run_task: false
    cleanup: false

  tasks:
  - name: Minikube Cleanup
    include_role:
      name: minikube
      tasks_from: minikube-cleanup.yml
    when:
      - cleanup|bool
      - run_task|bool

  - name: Install Minikube
    include_role:
      name: minikube
      tasks_from: install-minikube.yml
    when: run_task|bool

  - name: Install Openstack
    include_role:
      name: minikube
      tasks_from: install-osp.yml
